### ISSUE TITLE
After subscribing, Firefox's backarrow key takes user to a page that says, “Loading - Please wait” forever

### ISSUE THREAD

**Issue by randywsandberg** [Coded-Commerce-LLC/Benchmark-Email-WordPress-Legacy#12]
Steps to reproduce:
1. Using Mac Firefox, go to http://dev-benchmark-email-lite.pantheonsite.io
2. Complete all fields
3. Click Subscribe
4. Click browser backarrow

Result:
System stated, “Loading - Please wait” along with spinning wheel forever. Where “forever” equals at least 10 minutes. See screenshots 1 and 2.

Expected Result:
Expected fields to show and possibly data previously entered into fields as can be seen when using Mac Chrome. See screenshot 3 and 4.

Workaround:
No, other than reloading the page.

Reproducible?
Always

Occurs:
Mac Firefox 47.0 + WordPress 4.5.2 + Twenty Fifteen 1.5 + BMEL 2.6 [536c3f2]

Doesn’t Occur:
51.0.2704.84 (64-bit) + WordPress 4.5.2 + Twenty Fifteen 1.5 + BMEL 2.6 [536c3f2]

![screenshot 1](https://cloud.githubusercontent.com/assets/19829655/15993990/b0b712f8-30ab-11e6-8d5f-7e997cc06df2.png)
![screenshot 2](https://cloud.githubusercontent.com/assets/19829655/15993992/b0d13afc-30ab-11e6-8d20-41d0a2475ed6.png)
![screenshot 3](https://cloud.githubusercontent.com/assets/19829655/15993991/b0d057fe-30ab-11e6-9c7a-35f64b63825d.png)
![screenshot 4](https://cloud.githubusercontent.com/assets/19829655/15993993/b0d1a938-30ab-11e6-9e68-0152c5d609d5.png)

**Comment by randywsandberg** [comment]
Also occurs using:
Mac Firefox 47.0 + WordPress 4.5.2 + Twenty Sixteen 1.2 + BMEL 2.6 [536c3f2]

![screenshot 1](https://cloud.githubusercontent.com/assets/19829655/15994314/e517ac24-30b5-11e6-96d4-0ee9f2abcf93.png)

**Comment by seanconklin** [comment]
One option is to remove the Loading feature, as clicking BACK returns to the state the screen was left in before submitted, same if the submit button were disabled. Browsers do that to help users who filled out a form make adjustments. We might be able to force a PHP redirect after submission to force the browser to refresh the page in cache. I'll look into that.

There is a bigger fix for this using AJAX that requires an overhaul of that form to use AJAX instead of a standard form submission. It's not too large of a LOE, maybe a few hours, but it is invasive so that's something to consider for the next version.

**Comment by randywsandberg** [comment]
Still reproducible using WordPress 4.9 + Benchmark Email Lite 2.6 + Windows Firefox 57.0 (64-bit). And, NOT reproducible using Windows Google Chrome 62.0.3202.94 (Official Build) (64-bit) nor Microsoft Edge 41.16299.15.0. See updated Steps to reproduce:

1. Using Firefox, go to http://dev-benchmark-email-lite.pantheonsite.io
2. Complete all fields
3. Click Subscribe
4. Click browser backarrow

Thankfully it only seems to be reproducible in Firefox. That said, I wonder why? Anyway, I'll leave this one up to you to fix *or not!* ;-)

**Comment by randywsandberg** [comment]
**Setup:**
XAMPP for Linux 7.4.8
WordPress 5.4.2
Benchmark Email Lite 3.2
Linux Chrome 84.0.4147.89

Issue no longer reproducible due to functionality change. Closing as not to be fixed.
