### ISSUE TITLE
Subscription widget missing two fields (Date 1 Date 2 or Extra 1 Extra 2)

### ISSUE THREAD

**Issue by randywsandberg** [Coded-Commerce-LLC/Benchmark-Email-WordPress-Legacy#13]
Currently, our subscription widget mirrors all of the Option Fields at benchmarkemail.com except for two. That is, our widget currently displays Extra fields 3 through 6 (see Screenshot 1) but not Extra fields 1 and 2 (see Screenshot 2). The reason for this, of course, is because non-legacy Benchmark Email accounts no longer have "Extra 1" and "Extra 2" fields. That is, current Benchmark Email accounts have replaced the Extra 1 and 2 fields with "Date 1" and "Date 2" fields (see Screenshot 3).

So, my thinking here is maybe there's a way we could detect what kind of Benchmark Email account the person has and then display the appropriate field (i.e., legacy accounts see Extra 1 and 2 fields and new accounts see Date 1 and 2 fields). Just a thought! ;-)

![screenshot 1](https://cloud.githubusercontent.com/assets/19829655/16019169/7523e750-315c-11e6-8c6c-62a018e02656.png)
![screenshot 2](https://cloud.githubusercontent.com/assets/19829655/16019168/750e3220-315c-11e6-88d5-eef86f8e31c5.png)
![screenshot 3](https://cloud.githubusercontent.com/assets/19829655/16019170/75271308-315c-11e6-9148-89838054154f.png)

**Comment by seanconklin** [comment]
I know of no way to determine whether their list supports the newer Date 1 and Date 2 fields. I'm thinking we could add those fields in, provided they even work over the API, and have a footnote that they must exist on the list in order to work, or contact Benchmark Email to have your list upgraded before adding those to your form.

**Comment by randywsandberg** [comment]
I figured this was more of a question for the Benchmark Email folks to help us via the API differentiate between legacy and current accounts. Then, once we know what kind of account they have we could display the appropriate fields.

**Comment by randywsandberg** [comment]
**Setup:**
XAMPP for Linux 7.4.8
WordPress 5.4.2
Benchmark Email Lite 3.2
Linux Chrome 84.0.4147.89

Issue no longer reproducible due to functionality change. Closing as not to be fixed.
