### ISSUE TITLE
Our Opened Emails vs Benchmark Email's Email Opens Report

### ISSUE THREAD

**Issue by randywsandberg** [Coded-Commerce-LLC/Benchmark-Email-WordPress-Legacy#2]
Currently we display four columns. Starting with #, and followed by Name, Email, and Date (see Screenshot 1). Which is fine. But, at benchmarkemail.com, their's is done a bit differently and possibly better. They only display three columns beginning with Email (which includes both Name and Email), Device (which is really helpful!), and Date.

I'm not sure why we need the # column and it makes sense to group Name and Email together. Plus, take note that they allow the user to sort descending/ascending order on either the Email or Date columns. The default being the latest Date on top. Which, I believe, goes for ours as well.

Anyway, this isn't a bug but it is a possibly enhancement request. Or, at the very least, something to discuss at a later date. :-)

![screenshot 1](https://cloud.githubusercontent.com/assets/19829655/15952717/45eacfd0-2e78-11e6-95d9-d0054869eccc.png)
![screenshot 2](https://cloud.githubusercontent.com/assets/19829655/15952718/46095da6-2e78-11e6-9f6b-d8744202eb59.png)

**Comment by randywsandberg** [comment]
Also note that at the bottom of Benchmark Email's Email Opens Report page there are four very handy features; Save As List, Export As Excel, Export As CVS, and Records per page. See screenshot.

Just some more down-the-road ideas! :-)

![screenshot 1](https://cloud.githubusercontent.com/assets/19829655/15942482/71844f0c-2e39-11e6-8fb6-4f46e2ac9adb.png)

**Comment by seanconklin** [comment]
We checked today and the Device information is now in the API, so that can be added.

**Comment by randywsandberg** [comment]
**Setup:**
XAMPP for Linux 7.4.8
WordPress 5.4.2
Benchmark Email Lite 3.2
Linux Chrome 84.0.4147.89

Issue no longer reproducible due to UI change. Closing as not to be fixed.
