### ISSUE TITLE
Our Emails Bounced Report vs Benchmark Email's Email Bounce Report

### ISSUE THREAD

**Issue by randywsandberg** [Coded-Commerce-LLC/Benchmark-Email-WordPress-Legacy#4]
Currently we have four non-sortable columns; #, Name, Email, and Bounce Type (see Screenshot 1). Whereas at benchmarkemail.com they have only three columns; Email (which includes both Name and Email), Bounce Type, and Date. See Screenshot 2.

And beyond what has been shown in prior enhancement requests, beyond the ability to sort their Email or Date columns, their Bounce Type column allows the user to filter for Both (bounce types), Soft Bounces (only), or Hard Bounces (only). Both being the default. See screenshots 2 and 3.

And, as always it seems, the ever present Save As List, Export As Excel, Export As CVS, and the Records per page selector. See Screenshot 2.

![screenshot 1](https://cloud.githubusercontent.com/assets/19829655/15953214/396683ee-2e7d-11e6-879a-7437da9144fc.png)
![screenshot 2](https://cloud.githubusercontent.com/assets/19829655/15953216/397d56a0-2e7d-11e6-990e-48f314b5ca81.png)
![screenshot 3](https://cloud.githubusercontent.com/assets/19829655/15953215/397b91a8-2e7d-11e6-8f36-04f6044f0672.png)

**Comment by seanconklin** [comment]
I checked the communication log and the API does not provide us with the `Date` value, so that would be something to ask Benchmark Email to add on for us.

**Comment by randywsandberg** [comment]
**Setup:**
XAMPP for Linux 7.4.8
WordPress 5.4.2
Benchmark Email Lite 3.2
Linux Chrome 84.0.4147.89

Issue no longer reproducible due to functionality change. Closing as not to be fixed.
