### ISSUE TITLE
Missing Complaint Rate pages

### ISSUE THREAD

**Issue by randywsandberg** [Coded-Commerce-LLC/Benchmark-Email-WordPress-Legacy#7]
Steps to reproduce:
1. Go to http://dev-benchmark-email-lite.pantheonsite.io/wp-admin/
2. Log in as an admin
3. Go to BenchmarkEmail > Emails
4. Click on Introducing Bigcommerce for WordPress

Result:
Even though this particular report has an Abuse Report listed (see Screenshot 1), it was not clickable.

Expected result:
Not exactly sure what to expect here but at benchmarkemail.com, they have two different pages to go to. Top level looks like what can be seen in Screenshot 2. If one clicks View Details then they are taken to a page titled “Complaint Rate: Campaign-wide abuse complaints” (see Screenshot 3).

On the other hand, if they click the number (i.e., 1 in this case) either from the top level page (see Screenshot 2 again) or on the “Complaint Rate: Campaign-wide abuse complaints” page (see Screenshot 3 again) then they are taken to a page titled, “Complaint Rate: Abuse complaints by ISP” (see Screenshot 4). From this page one can click the view for all campaigns link to be taken back to the “Complaint Rate: Campaign-wide abuse complaints” page.

Workaround?
No

Reproducible?
Always

Occurs:
- Mac Safari 9.1.1 + latest DEV BMEL
- Mac Firefox 47.0 + Latest DEV BMEL

![screenshot 1](https://cloud.githubusercontent.com/assets/19829655/15953118/0de5d68a-2e7c-11e6-9f62-db162e2185c5.png)
![screenshot 2](https://cloud.githubusercontent.com/assets/19829655/15953115/0de0930a-2e7c-11e6-967c-a9ff26604e13.png)
![screenshot 3](https://cloud.githubusercontent.com/assets/19829655/15953116/0de0ea1c-2e7c-11e6-8a8a-17171440c345.png)
![screenshot 4](https://cloud.githubusercontent.com/assets/19829655/15953117/0de2f3a2-2e7c-11e6-8ed7-6df6e011127d.png)

**Comment by seanconklin** [comment]
The current API v1.3 does not offer this information. We could link the users over to https://ui.benchmarkemail.com/Reports/Abuse but that would require opening a new tab and logging into Benchmark Email GUI.

Here's the current Report related methods we have access to:
reportGet ( string token, string filter, integer pageNumber, integer pageSize, string orderBy, string sortOrder ) 
Get the list of sent campaign using the filter and paging limits, ordered by the name or date of the campaign.
reportGetBounces ( string token, string emailID, integer pageNumber, integer pageSize, string Filter, string orderBy, string sortOrder ) 
Get the email addresses which bounced in a given campaign,using the paging limits, ordered by the email or date of the bounced record.
reportGetClicks ( string token, string emailID ) 
Get the email addresses which bounced in a given campaign,using the paging limits, ordered by the email or date of the bounced record.
reportGetEmailLinks ( string token, string emailID ) 
Get the Link URLS for the given campaign.
reportGetClickEmails ( string token, string emailID, string clickUrl, integer pageNumber, integer pageSize, string orderBy, string sortOrder ) 
Get the Emails of the receipients clicking on URLs for a campaign ,using the paging limits.
reportGetForwards ( string token, string emailID, integer pageNumber, integer pageSize, string orderBy, string sortOrder ) 
Get the email addresses to which the given campaign was forwarded,using the paging limits, ordered by the email or date of the forwarded record.
reportGetHardBounces ( string token, string emailID, integer pageNumber, integer pageSize, string orderBy, string sortOrder ) 
Get the email addresses which hard bounced in a given campaign,using the paging limits, ordered by the email or date of the bounced record.
reportGetSoftBounces ( string token, string emailID, integer pageNumber, integer pageSize, string orderBy, string sortOrder ) 
Get the email addresses which soft bounced in a given campaign,using the paging limits, ordered by the email or date of the bounced record.
reportGetOpens ( string token, string emailID, integer pageNumber, integer pageSize, string orderBy, string sortOrder ) 
Get the email addresses which were opened in a given campaign,using the paging limits, ordered by the email or date of the opened record.
reportGetUnopens ( string token, string emailID, integer pageNumber, integer pageSize, string orderBy, string sortOrder ) 
Get the email addresses which were neither opened nor bounced in a given campaign,using the paging limits, ordered by the email or date of the opened record.
reportGetUnsubscribes ( string token, string emailID, integer pageNumber, integer pageSize, string orderBy, string sortOrder ) 
Get the email addresses which unsubscribed in a given campaign,using the paging limits, ordered by the email or date of the unsubscribe record.
reportGetSummary ( string token, string emailID ) 
Get the summary of an email campaign.
reportCompare ( string token, string emailID ) 
Get the summary of more than one email campaign.
reportGetOpenCountry ( string token, string emailID ) 
Get the list of Countries with there region code and opent Count
reportGetOpenForCountry ( string token, string emailID, string CountryCode ) 
Get the list of Regions of a country with there opent Count

**Comment by randywsandberg** [comment]
Still reproducible using WordPress 4.9 + Benchmark Email Lite 2.6 + Google Chrome Version 62.0.3202.94 (Official Build) (64-bit) as well as Firefox 57.0 (64-bit). See updated Steps to reproduce:

1. Go to http://make.beautomated.com/wp-admin/
2. Log in as admin
3.  Go to BenchmarkEmail > Emails
4. Click on Introducing Bigcommerce for WordPress

Given what you've said about Sean, we need to reclassify this as an enhancement request.

**Comment by randywsandberg** [comment]
**Setup:**
XAMPP for Linux 7.4.8
WordPress 5.4.2
Benchmark Email Lite 3.2
Linux Chrome 84.0.4147.89

Issue no longer reproducible due to functionality change. Closing as not to be fixed.
